server: 
  port: 8080
spring: 
  application: 
    name: agent-police
eureka:
  client: 
    #10秒获取一次服务列表
    registry-fetch-interval-seconds: 10
    service-url: 
      defaultZone: http://slave1:8761/eureka/,http://slave2:8762/eureka/   

